# Generated by Django 3.0.3 on 2020-12-04 15:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('car_license_plate', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='Car_brand',
            fields=[
                ('car_brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_brand_name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'car_brand',
            },
        ),
        migrations.CreateModel(
            name='Car_type',
            fields=[
                ('car_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_type_name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'car_type',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=180, null=True)),
                ('company_is_active', models.BooleanField(default=False)),
                ('created_on', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Device_model',
            fields=[
                ('device_model_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_model_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'device_model',
            },
        ),
        migrations.CreateModel(
            name='Device_type',
            fields=[
                ('device_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_type_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'device_type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('user_lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('user_mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('user_citizen_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='User_has_car',
            fields=[
                ('user_has_car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
            options={
                'db_table': 'user_has_car',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(blank=True, max_length=100, null=True)),
                ('event_public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Car')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Device_model')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Device_type')),
            ],
            options={
                'db_table': 'device',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='car_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Car_brand'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Car_type'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('admin_username', models.CharField(max_length=100, unique=True)),
                ('admin_password', models.CharField(blank=True, max_length=80, null=True)),
                ('admin_is_active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
