# Generated by Django 3.0.3 on 2020-12-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='car',
        ),
        migrations.AddField(
            model_name='event',
            name='event_license_plate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
