# Generated by Django 3.0.3 on 2020-12-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201205_1837'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_has_car',
            new_name='Users_has_car',
        ),
        migrations.RenameField(
            model_name='users_has_car',
            old_name='Users',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='users_has_car',
            old_name='user_has_car_id',
            new_name='users_has_car_id',
        ),
    ]
